/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import ufuacademi.Aluno;
import ufuacademi.UFUAcademi;
import ufuacademi.ValidaCPF;
import ufuacademi.exceptions.CpfInvalidException;
import ufuacademi.exceptions.EmptyNameException;

/**
 * JFrame CadastrarAlunos
 */
public class CadastrarAlunos extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAlunos
     */
    public CadastrarAlunos() {
        initComponents();
                Color cinza = new Color(80, 80, 80);
        getContentPane().setBackground(cinza);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoButtonGroup = new javax.swing.ButtonGroup();
        cpfTextField = new javax.swing.JTextField();
        cadastrarAlunoButton = new javax.swing.JButton();
        dataNascimentoTextField = new javax.swing.JTextField();
        enderecoLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        sexoFemininoCheckBox = new javax.swing.JCheckBox();
        cpfLabel = new javax.swing.JLabel();
        sexoMasculinoCheckBox = new javax.swing.JCheckBox();
        dataNascimentoLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        enderecoTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        dataNascimentoFormatoLabel = new javax.swing.JLabel();
        cpfFormatoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(80, 80, 80));
        setResizable(false);

        cpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextFieldActionPerformed(evt);
            }
        });

        cadastrarAlunoButton.setText("CADASTRAR ALUNO");
        cadastrarAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunoButtonActionPerformed(evt);
            }
        });

        enderecoLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        enderecoLabel.setForeground(new java.awt.Color(255, 255, 255));
        enderecoLabel.setText("ENDERECO:");

        sexoLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        sexoLabel.setForeground(new java.awt.Color(255, 255, 255));
        sexoLabel.setText("SEXO:");

        sexoButtonGroup.add(sexoFemininoCheckBox);
        sexoFemininoCheckBox.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        sexoFemininoCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        sexoFemininoCheckBox.setText("Feminino");
        sexoFemininoCheckBox.setContentAreaFilled(false);
        sexoFemininoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoFemininoCheckBoxActionPerformed(evt);
            }
        });

        cpfLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(255, 255, 255));
        cpfLabel.setText("CPF:");

        sexoButtonGroup.add(sexoMasculinoCheckBox);
        sexoMasculinoCheckBox.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        sexoMasculinoCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        sexoMasculinoCheckBox.setText("Masculino");
        sexoMasculinoCheckBox.setContentAreaFilled(false);
        sexoMasculinoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoMasculinoCheckBoxActionPerformed(evt);
            }
        });

        dataNascimentoLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        dataNascimentoLabel.setForeground(new java.awt.Color(255, 255, 255));
        dataNascimentoLabel.setText("DATA DE NASCIMENTO:");

        tituloLabel.setFont(new java.awt.Font("Lato Black", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("CADASTRO DE ALUNOS");

        nomeLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeLabel.setText("NOME COMPLETO:");

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LOGO UFUACADEMI.png"))); // NOI18N

        dataNascimentoFormatoLabel.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        dataNascimentoFormatoLabel.setForeground(new java.awt.Color(255, 255, 255));
        dataNascimentoFormatoLabel.setText("aaaa-mm-dd");

        cpfFormatoLabel.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        cpfFormatoLabel.setForeground(new java.awt.Color(255, 255, 255));
        cpfFormatoLabel.setText("Insira apenas digitos.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enderecoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enderecoTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sexoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoMasculinoCheckBox)
                            .addComponent(sexoFemininoCheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpfLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cpfFormatoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataNascimentoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataNascimentoFormatoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(cadastrarAlunoButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tituloLabel)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoLabel)
                    .addComponent(dataNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascimentoFormatoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfFormatoLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoLabel)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLabel)
                    .addComponent(sexoFemininoCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexoMasculinoCheckBox)
                .addGap(18, 18, 18)
                .addComponent(cadastrarAlunoButton)
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldActionPerformed

    private void cadastrarAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunoButtonActionPerformed
        String nome = nomeTextField.getText();
        String dataNascimento = dataNascimentoTextField.getText().trim();
        String cpf = cpfTextField.getText();
        String endereco = enderecoTextField.getText();
        String sexo;
        if (sexoFemininoCheckBox.isSelected()) sexo = "Feminino";
        else if (sexoMasculinoCheckBox.isSelected()) sexo = "Masculino";
        else sexo = null;
        try{
            LocalDate dataNascimentoLocalDate = LocalDate.parse(dataNascimento);
            
            Pattern cpfPattern = Pattern.compile("\\d{11}");
            boolean cpfEstaNoFormato = cpfPattern.matcher(cpf).matches();
            if (!cpfEstaNoFormato) throw new CpfInvalidException();
            if(!ValidaCPF.isCPF(cpf)) throw new CpfInvalidException();
            cpf = ValidaCPF.imprimeCPF(cpf);
            
            boolean nomeEstaVazio = nome.trim().isEmpty();
            if (nomeEstaVazio) throw new EmptyNameException();
            
            Aluno aluno = new Aluno(nome, dataNascimento, cpf, endereco, sexo);
            boolean foiCadastrado = UFUAcademi.gerenciadorAlunos.novo(aluno);
            if(foiCadastrado) super.dispose();
        }
        catch (DateTimeParseException ex){
            JOptionPane.showMessageDialog(null,"A data inserida não corresponde ao formato indicado.","Formato de Data Errado.",JOptionPane.ERROR_MESSAGE);
        }
        catch (CpfInvalidException ex){
            JOptionPane.showMessageDialog(null,"O CPF inserido não corresponde ao formato indicado.","Formato de CPF Errado.",JOptionPane.ERROR_MESSAGE);
        }
        catch (EmptyNameException ex){
            JOptionPane.showMessageDialog(null,"O nome inserido não contêm caracteres.","Nome Inválido.",JOptionPane.ERROR_MESSAGE);   
        }
        
    }//GEN-LAST:event_cadastrarAlunoButtonActionPerformed

    private void sexoFemininoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoFemininoCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoFemininoCheckBoxActionPerformed

    private void sexoMasculinoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoMasculinoCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoMasculinoCheckBoxActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarAlunoButton;
    private javax.swing.JLabel cpfFormatoLabel;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JLabel dataNascimentoFormatoLabel;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JTextField dataNascimentoTextField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.ButtonGroup sexoButtonGroup;
    private javax.swing.JCheckBox sexoFemininoCheckBox;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JCheckBox sexoMasculinoCheckBox;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
