/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import java.awt.Color;
import java.util.ArrayList;
import ufuacademi.Atividade;
import ufuacademi.UFUAcademi;

/**
 * JFrame EscolherAtividade
 */
public class EscolherAtividade extends javax.swing.JFrame {
    public static int indiceAtividadeEscolhida;
    /**
     * Creates new form EscolherAtividade
     */
    public EscolherAtividade() {
        initComponents();
        Color cinza = new Color(80, 80, 80);
        getContentPane().setBackground(cinza);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        atividadeLabel = new javax.swing.JLabel();
        atividadeComboBox = new javax.swing.JComboBox<>();
        editarButton = new javax.swing.JButton();
        deletarButton = new javax.swing.JButton();
        visualizarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LOGO UFUACADEMI.png"))); // NOI18N

        tituloLabel.setFont(new java.awt.Font("Lato Black", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("ESCOLHER ATIVIDADE");

        atividadeLabel.setForeground(new java.awt.Color(255, 255, 255));
        atividadeLabel.setText("Atividade");

        atividadeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividadeComboBoxActionPerformed(evt);
            }
        });

        editarButton.setText("EDITAR");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        deletarButton.setText("DELETAR");
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });

        visualizarButton.setText("VISUALIZAR");
        visualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atividadeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deletarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atividadeLabel)
                            .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloLabel)
                        .addGap(18, 18, 18)
                        .addComponent(atividadeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atividadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarButton)
                            .addComponent(visualizarButton)
                            .addComponent(deletarButton))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        EditarAtividades editarAtividades = new EditarAtividades();
        String codigo = UFUAcademi.gerenciadorAtividades.getListaAtividades().get(atividadeComboBox.getSelectedIndex()).getCodigo();
        String nome = UFUAcademi.gerenciadorAtividades.getListaAtividades().get(atividadeComboBox.getSelectedIndex()).getNome();
        String descricao = UFUAcademi.gerenciadorAtividades.getListaAtividades().get(atividadeComboBox.getSelectedIndex()).getDescricao();
        String categoria = UFUAcademi.gerenciadorAtividades.getListaAtividades().get(atividadeComboBox.getSelectedIndex()).getCategoria();
        editarAtividades.setTextFields(codigo,nome,descricao,categoria);
        editarAtividades.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_editarButtonActionPerformed

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        if(indiceAtividadeEscolhida>=0){
            UFUAcademi.gerenciadorAtividades.deletar(indiceAtividadeEscolhida);
            atividadeComboBox.removeItemAt(indiceAtividadeEscolhida);
        }
        super.dispose();
        //Bug Aqui
        //if (!UFUAcademi.gerenciadorAtividades.getListaAtividades().isEmpty()) indiceAlunoEscolhido--;
    }//GEN-LAST:event_deletarButtonActionPerformed

    private void visualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarButtonActionPerformed
        Sobre visualizarAtividade = new Sobre();
        visualizarAtividade.setTextArea(UFUAcademi.gerenciadorAtividades.getListaAtividades().get(atividadeComboBox.getSelectedIndex()).toString());
        visualizarAtividade.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_visualizarButtonActionPerformed

    private void atividadeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividadeComboBoxActionPerformed
        indiceAtividadeEscolhida = atividadeComboBox.getSelectedIndex();
    }//GEN-LAST:event_atividadeComboBoxActionPerformed
    /**
     * Carrega o elemento ComboBox com as Categorias e os Códigos das Atividades
     */
    public void setAtividadeComboBox(){
        ArrayList<Atividade> atividades = UFUAcademi.gerenciadorAtividades.getListaAtividades();
        for (Atividade atividade: atividades){
            atividadeComboBox.addItem(atividade.getCategoria()+": "+atividade.getCodigo());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherAtividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> atividadeComboBox;
    private javax.swing.JLabel atividadeLabel;
    private javax.swing.JButton deletarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton visualizarButton;
    // End of variables declaration//GEN-END:variables
}
