/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import java.awt.Color;
import java.util.ArrayList;
import ufuacademi.Aluno;
import ufuacademi.UFUAcademi;

/**
 * JFrame EscolherAluno
 */
public class EscolherAluno extends javax.swing.JFrame {
    public static int indiceAlunoEscolhido;
    /**
     * Creates new form EscolherAluno
     */
    public EscolherAluno() {
        initComponents();
        Color cinza = new Color(80, 80, 80);
        getContentPane().setBackground(cinza);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        alunoLabel = new javax.swing.JLabel();
        alunoComboBox = new javax.swing.JComboBox<>();
        editarButton = new javax.swing.JButton();
        deletarButton = new javax.swing.JButton();
        visualizarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LOGO UFUACADEMI.png"))); // NOI18N

        tituloLabel.setFont(new java.awt.Font("Lato Black", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("ESCOLHER ALUNO");

        alunoLabel.setForeground(new java.awt.Color(255, 255, 255));
        alunoLabel.setText("Aluno:");

        alunoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoComboBoxActionPerformed(evt);
            }
        });

        editarButton.setText("EDITAR");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        deletarButton.setText("DELETAR");
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });

        visualizarButton.setText("VISUALIZAR");
        visualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alunoLabel)
                    .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(deletarButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(visualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editarButton))
                        .addComponent(alunoComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(tituloLabel)
                        .addGap(18, 18, 18)
                        .addComponent(alunoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(alunoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarButton)
                            .addComponent(deletarButton)
                            .addComponent(visualizarButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alunoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoComboBoxActionPerformed
        indiceAlunoEscolhido = alunoComboBox.getSelectedIndex();
    }//GEN-LAST:event_alunoComboBoxActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        EditarAlunos editarAlunos = new EditarAlunos();
        String nome = UFUAcademi.gerenciadorAlunos.getListaAlunos().get(alunoComboBox.getSelectedIndex()).getNome();
        String dataNascimento = UFUAcademi.gerenciadorAlunos.getListaAlunos().get(alunoComboBox.getSelectedIndex()).getDataNascimento();
        String cpf = UFUAcademi.gerenciadorAlunos.getListaAlunos().get(alunoComboBox.getSelectedIndex()).getCpf();
        String endereco = UFUAcademi.gerenciadorAlunos.getListaAlunos().get(alunoComboBox.getSelectedIndex()).getEndereco();
        String sexo = UFUAcademi.gerenciadorAlunos.getListaAlunos().get(alunoComboBox.getSelectedIndex()).getSexo();
        editarAlunos.setTextFields(nome,dataNascimento,cpf,endereco, sexo);
        editarAlunos.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_editarButtonActionPerformed

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        if(indiceAlunoEscolhido>=0){
            UFUAcademi.gerenciadorAlunos.deletar(indiceAlunoEscolhido);
            alunoComboBox.removeItemAt(indiceAlunoEscolhido);
        }
        //Bug não crítico
        //if (!UFUAcademi.gerenciadorAlunos.getListaAlunos().isEmpty()) indiceAlunoEscolhido--;
        super.dispose();
    }//GEN-LAST:event_deletarButtonActionPerformed

    private void visualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarButtonActionPerformed
        Sobre visualizarAluno = new Sobre();
        visualizarAluno.setTextArea(UFUAcademi.gerenciadorAlunos.getListaAlunos().get(alunoComboBox.getSelectedIndex()).toString());
        visualizarAluno.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_visualizarButtonActionPerformed
    /**
     * Carrega o elemento ComboBox com os nomes dos Alunos
     */
    public void setAlunoComboBox(){
        ArrayList<Aluno> alunos = UFUAcademi.gerenciadorAlunos.getListaAlunos();
        for (Aluno aluno: alunos){
            alunoComboBox.addItem(aluno.getNome());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherAluno().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alunoComboBox;
    private javax.swing.JLabel alunoLabel;
    private javax.swing.JButton deletarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton visualizarButton;
    // End of variables declaration//GEN-END:variables
}
